name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: olegtarasov/download-nuget@v1
    - name: compile
      run: D:\a\c-plus-plus-nuget-sample\c-plus-plus-nuget-sample\run.bat
    - name: pack
      run: nuget pack package
