name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: build
      run: dir C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise
    - name: build2
      run: dir C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7
    - name: build3
      run: dir C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE
